### ISSUE TITLE
Basic Search Follow Up - Error on bad search term.

### ISSUE THREAD

**Issue by tristan-hyams** [ofpinewood/pineblog#117]
@petervandenhout So sorry for the long delay. Life has a way of sneaking up on you.

Search functionality was great. Problem did occur for me on querying something that doesn't exist. I.e., I tested random strings. Search throws an uncaught exception if the term doesn't exist it appears.

Edit:
More testing -> other random terms worked though.
![image](https://user-images.githubusercontent.com/1414138/115153178-b03cea80-a042-11eb-948f-c6bd764ca826.png)

It seems related to having the key word `test` in the query.
![image](https://user-images.githubusercontent.com/1414138/115153222-d06ca980-a042-11eb-8751-941db007cf3b.png)

Possible fix for the code:
I have a feeling `IEnumerable posts` was null vs. empty.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Opw.PineBlog.Posts.SearchPostsQuery.Handler.RankPosts(IEnumerable`1 posts, String query)
   at Opw.PineBlog.Posts.SearchPostsQuery.Handler.Handle(SearchPostsQuery request, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Opw.PineBlog.RazorPages.Areas.Blog.Pages.IndexModel.OnGetAsync(CancellationToken cancellationToken, Int32 page, String category, String q)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
   
Simpler reproducible.
![image](https://user-images.githubusercontent.com/1414138/115152442-17f13680-a03f-11eb-9eef-430ac38bfb4d.png)

Which means RankPosts() could be solved this way but you may want to solve it differently internally yourself. I will leave it up to you as its possible a bug is being created elsewhere and the list should not be null (i.e. empty).

```csharp
if (posts != null)
{
    foreach (var post in posts)
    {
        var rank = 0;
        foreach (var term in terms)
        {
            int hits;
            if (post.Title.ToLower().Contains(term))
            {
                hits = Regex.Matches(post.Title.ToLower(), term).Count;
                rank += hits * 10;
            }
            if (post.Categories.ToLower().Contains(term))
            {
                hits = Regex.Matches(post.Categories.ToLower(), term).Count;
                rank += hits * 10;
            }
            if (post.Description.ToLower().Contains(term))
            {
                hits = Regex.Matches(post.Description.ToLower(), term).Count;
                rank += hits * 3;
            }
            if (post.Content.ToLower().Contains(term))
            {
                hits = Regex.Matches(post.Content.ToLower(), term).Count;
                rank += hits * 1;
            }
        }

        rankedPosts.Add(new Tuple<Post, int>(post, rank));
    }
}
```

This solution has you still return an empty RankedPosts List<Tuple> and should still work with pre-existing code.

https://github.com/ofpinewood/pineblog/blob/4694ec446500fe95ea7b793c03033eda4f355782/src/Opw.PineBlog.Core/Posts/SearchPostsQuery.cs#L161

Thanks again for your hard work!

**Comment by petervandenhout** [comment]
@houseofcat yes that looks like a null reference exception in the RankPosts method. I'll add some tests for this case and will try your fix. Thanks for catching this one!

**Comment by petervandenhout** [comment]
@houseofcat I've added fixes for the NullReferenceException. They are available in v2.1.1. 
Can you check if this solves the problem also for you?

**Comment by tristan-hyams** [comment]
I will check later today!

**Comment by tristan-hyams** [comment]
I mean 5 days later!

Issue resolved, thank you.
