### ISSUE TITLE
Unable to start app with PineBlog: Invalid object name 'PineBlog_BlogSettings'.

### ISSUE THREAD

**Issue by ajtatum** [ofpinewood/pineblog#98]
If it makes any difference, I'm using UserSecrets during development and Azure Key Vault in Staging/Production environments, so while I do have an appsettings file, all it contains is logging configuration. This is what my ConfigureAppConfiguration looks like:

```
.ConfigureAppConfiguration((hostContext, configApp) =>
{
    configApp.SetBasePath(Directory.GetCurrentDirectory());
    configApp.AddJsonFile("appsettings.json", false, true);
    configApp.AddJsonFile($"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json", true, true);
    configApp.AddEnvironmentVariables();
    configApp.AddCommandLine(args);

    if (hostContext.HostingEnvironment.IsDevelopment())
    {
        configApp.AddUserSecrets<Program>();
    }
    else
    {
        var azureServiceTokenProvider = new AzureServiceTokenProvider();
        var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));

        configApp.AddAzureKeyVault(new AzureKeyVaultConfigurationOptions()
        {
            Client = keyVaultClient,
            Manager = new DefaultKeyVaultSecretManager(),
            Vault = $"https://{Environment.GetEnvironmentVariable("AzureKeyVaultName")}.vault.azure.net/",
            ReloadInterval = TimeSpan.FromMinutes(30)
        });
    }

    configApp.AddPineBlogConfiguration(reloadOnChange: true);
})
```

In my secrets.json file, I have the following:

"PineBlogOptions": {
        "Title": "PineBlog",
        "Description": "A blogging engine based on ASP.NET Core MVC Razor Pages and Entity Framework Core",
        "ItemsPerPage": 5,
        "CreateAndSeedDatabases": true,
        "ConnectionStringName": "DefaultConnection",
        "AzureStorageConnectionString": "myazurestorageconnectionstring",
        "AzureStorageBlobContainerName": "blog",
        "FileBaseUrl": "https://mystorageaccount.blob.core.windows.net/"
    }

I have the code in the Startup file as documented, but it doesn't seem to get that far. It fails upon starting up, with an error that almost seems like it's expecting tables to be there. I tried figuring out if I needed to add something somewhere to seed the database, but I can't seem to find it in the documentation (sorry if I missed it.). Here's the full error when I start the application:

Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'PineBlog_BlogSettings'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   at Opw.PineBlog.EntityFrameworkCore.BlogSettingsConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at App.Web.Program.Main(String[] args) in C:\repos\source\App\App.Web\Program.cs:line 32
   at App.Web.Program.<Main>(String[] args)
ClientConnectionId:d6a5ab15-b0f2-46bd-8a3f-ad2a642d1ea0
Error Number:208,State:1,Class:16

Any assistance would be greatly appreciated. I believe this is exactly what I'm looking for, a way to add a blog to my existing application and use my existing user base for authentication/authorization, etc. If the settings absolutely need to be in appSettings, I'm not sure what to do as I'm not going to put my SQL connection string in the appsettings file. 

Thank you,
AJ

**Comment by petervandenhout** [comment]
@ajtatum I'll look into this later today. I think I know what the underlying issue is, so it should not be a difficult fix.

**Comment by petervandenhout** [comment]
@ajtatum version 1.3.4 has been released containing a fix for the issue.
https://github.com/ofpinewood/pineblog/releases/tag/1.3.4

**Comment by ajtatum** [comment]
The got me up and running! Thank you! However, there are other issues cropping up... it's almost as if it's not pulling in the RazorPages package or something as it's throwing 404 errors for theme.js, admin.js, and a bunch of jQuery things. I'll post another ticket with more details. Thank you for taking care of this one so quickly!
